using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ReunionMovement.SourceGenerator
{
    /// <summary>
    /// 源码生成器 —— 扫描 ReunionMovement.Core.UI 命名空间下所有 UIController 子类，
    /// 生成 name → Type 的静态注册表，替代 UISystem.CreateUIController 的运行时
    /// AppDomain.GetAssemblies() + GetType 反射。
    /// </summary>
    [Generator]
    public class UIControllerRegistryGenerator : ISourceGenerator
    {
        private const string UIControllerMetadataName = "ReunionMovement.Core.UI.UIController";
        private const string TargetNamespace = "ReunionMovement.Core.UI";

        public void Initialize(GeneratorInitializationContext context) { }

        public void Execute(GeneratorExecutionContext context)
        {
            var uiControllerSymbol = context.Compilation.GetTypeByMetadataName(UIControllerMetadataName);
            if (uiControllerSymbol == null)
            {
                // UIController 不在本编译中（例如纯 Editor 程序集），跳过
                return;
            }

            // 仅当 UIController 由当前编译的程序集定义时才生成，
            // 否则会在引用 Assembly-CSharp 的插件程序集编译时重复生成同名类（CS0436/CS0101）
            if (!SymbolEqualityComparer.Default.Equals(uiControllerSymbol.ContainingAssembly, context.Compilation.Assembly))
            {
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> by ReunionMovement.SourceGenerator / UIControllerRegistryGenerator</auto-generated>");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine($"namespace {TargetNamespace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>编译期生成的 UI 控制器注册表（替代运行时反射）</summary>");
            sb.AppendLine("    public static class UIControllerRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        private static readonly Dictionary<string, Type> s_map = new Dictionary<string, Type>(StringComparer.Ordinal)");
            sb.AppendLine("        {");

            foreach (var type in EnumerateNamedTypes(context.Compilation))
            {
                if (!InheritsFrom(type, uiControllerSymbol)) continue;
                if (type.IsAbstract) continue;
                if (type.IsGenericType) continue;

                string fullName = type.ToDisplayString();
                sb.AppendLine($"            {{ \"{type.Name}\", typeof({fullName}) }},");
            }

            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>按 UI 名称查找控制器类型（零反射）</summary>");
            sb.AppendLine("        public static bool TryGet(string uiName, out Type type) => s_map.TryGetValue(uiName, out type);");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            // 注意：即使条目为空也必须生成类（空注册表）：
            // 1) UIController 子类可能位于其他程序集（如预定义 Assembly-CSharp 中的 GenerateScript/UI），
            //    本编译扫描不到子类，但 UISystem.CreateUIController 仍引用 UIControllerRegistry.TryGet，
            //    空注册表 + UISystem 的反射回退保证跨程序集 UI 控制器正常加载。
            // 2) 与 TerminalCommandRegistryGenerator 保持一致（空表也生成）。
            context.AddSource("ReunionMovement.UIControllerRegistry.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static bool InheritsFrom(INamedTypeSymbol type, INamedTypeSymbol baseType)
        {
            var current = type.BaseType;
            while (current != null)
            {
                if (SymbolEqualityComparer.Default.Equals(current, baseType)) return true;
                current = current.BaseType;
            }
            return false;
        }

        private static IEnumerable<INamedTypeSymbol> EnumerateNamedTypes(Compilation compilation)
        {
            foreach (var tree in compilation.SyntaxTrees)
            {
                var model = compilation.GetSemanticModel(tree);
                foreach (var node in tree.GetRoot()
                             .DescendantNodes()
                             .OfType<TypeDeclarationSyntax>())
                {
                    if (model.GetDeclaredSymbol(node) is INamedTypeSymbol symbol)
                    {
                        yield return symbol;
                    }
                }
            }
        }
    }
}
